---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
script:
  - bundle exec rackup test/fake_app.rb &
  - bundle exec rake test

before_install:
  - gem install bundler -v 2.0.1
notifications:
  email: false
